export const baseLanguageOptions = [
  { code: "auto", name: "Auto-detect", voiceName: "" },
  { code: "en", name: "English", voiceName: "en-US-Wavenet-D" },
  { code: "es", name: "Spanish", voiceName: "es-ES-Wavenet-B" },
  { code: "fr", name: "French", voiceName: "fr-FR-Wavenet-B" },
  { code: "de", name: "German", voiceName: "de-DE-Wavenet-B" },
  { code: "it", name: "Italian", voiceName: "it-IT-Wavenet-B" },
  { code: "pt", name: "Portuguese", voiceName: "pt-PT-Wavenet-B" },
  { code: "ru", name: "Russian", voiceName: "ru-RU-Wavenet-B" },
  { code: "ja", name: "Japanese", voiceName: "ja-JP-Wavenet-B" },
  { code: "ko", name: "Korean", voiceName: "ko-KR-Wavenet-B" },
  { code: "zh", name: "Chinese", voiceName: "cmn-CN-Wavenet-B" },
  { code: "ar", name: "Arabic", voiceName: "ar-XA-Wavenet-B" },
  { code: "hi", name: "Hindi", voiceName: "hi-IN-Wavenet-A" },
  { code: "pa", name: "Punjabi", voiceName: "pa-IN-Standard-A" },
  { code: "gu", name: "Gujarati", voiceName: "gu-IN-Standard-A" },
  { code: "bn", name: "Bengali", voiceName: "bn-IN-Standard-A" },
  { code: "ta", name: "Tamil", voiceName: "ta-IN-Wavenet-A" },
  { code: "te", name: "Telugu", voiceName: "te-IN-Standard-A" },
  { code: "ml", name: "Malayalam", voiceName: "ml-IN-Standard-A" },
  {
    code: "zh-CN",
    name: "Chinese (Simplified)",
    voiceName: "cmn-CN-Wavenet-B",
  },
  {
    code: "zh-TW",
    name: "Chinese (Traditional)",
    voiceName: "cmn-TW-Wavenet-A",
  },
  { code: "mr", name: "Marathi", voiceName: "mr-IN-Standard-A" },
  { code: "ur", name: "Urdu", voiceName: "ur-IN-Standard-A" },
  { code: "tr", name: "Turkish", voiceName: "tr-TR-Wavenet-B" },
  { code: "vi", name: "Vietnamese", voiceName: "vi-VN-Wavenet-B" },
  { code: "id", name: "Indonesian", voiceName: "id-ID-Wavenet-B" },
  { code: "th", name: "Thai", voiceName: "th-TH-Wavenet-B" },
  { code: "pl", name: "Polish", voiceName: "pl-PL-Wavenet-B" },
  { code: "uk", name: "Ukrainian", voiceName: "uk-UA-Wavenet-B" },
  { code: "ro", name: "Romanian", voiceName: "ro-RO-Wavenet-B" },
  { code: "nl", name: "Dutch", voiceName: "nl-NL-Wavenet-B" },
  { code: "sv", name: "Swedish", voiceName: "sv-SE-Wavenet-B" },
  { code: "fi", name: "Finnish", voiceName: "fi-FI-Wavenet-B" },
  { code: "no", name: "Norwegian", voiceName: "nb-NO-Wavenet-B" },
  { code: "da", name: "Danish", voiceName: "da-DK-Wavenet-B" },
  { code: "cs", name: "Czech", voiceName: "cs-CZ-Wavenet-B" },
  { code: "el", name: "Greek", voiceName: "el-GR-Wavenet-B" },
  { code: "he", name: "Hebrew", voiceName: "he-IL-Wavenet-B" },
  { code: "hu", name: "Hungarian", voiceName: "hu-HU-Wavenet-B" },
  { code: "uz", name: "Uzbek", voiceName: "uz-UZ-Standard-A" },
];

export const languageOptions = [
  { code: "en", name: "English", voiceName: "en-US-Wavenet-D" },
  { code: "hi", name: "Hindi", voiceName: "hi-IN-Wavenet-A" },
  { code: "es", name: "Spanish", voiceName: "es-ES-Wavenet-B" },
  { code: "fr", name: "French", voiceName: "fr-FR-Wavenet-B" },
  { code: "de", name: "German", voiceName: "de-DE-Wavenet-B" },
  { code: "it", name: "Italian", voiceName: "it-IT-Wavenet-B" },
  { code: "pt", name: "Portuguese", voiceName: "pt-PT-Wavenet-B" },
  { code: "ru", name: "Russian", voiceName: "ru-RU-Wavenet-B" },
  { code: "ja", name: "Japanese", voiceName: "ja-JP-Wavenet-B" },
  { code: "ko", name: "Korean", voiceName: "ko-KR-Wavenet-B" },
  {
    code: "zh-CN",
    name: "Chinese (Simplified)",
    voiceName: "cmn-CN-Wavenet-B",
  },
  {
    code: "zh-TW",
    name: "Chinese (Traditional)",
    voiceName: "cmn-TW-Wavenet-A",
  },
  { code: "ar", name: "Arabic", voiceName: "ar-XA-Wavenet-B" },
  { code: "bn", name: "Bengali", voiceName: "bn-IN-Standard-A" },
  { code: "pa", name: "Punjabi", voiceName: "pa-IN-Standard-A" },
  { code: "gu", name: "Gujarati", voiceName: "gu-IN-Standard-A" },
  { code: "ta", name: "Tamil", voiceName: "ta-IN-Wavenet-A" },
  { code: "te", name: "Telugu", voiceName: "te-IN-Standard-A" },
  { code: "ml", name: "Malayalam", voiceName: "ml-IN-Standard-A" },
  { code: "mr", name: "Marathi", voiceName: "mr-IN-Standard-A" },
  { code: "ur", name: "Urdu", voiceName: "ur-IN-Standard-A" },
  { code: "tr", name: "Turkish", voiceName: "tr-TR-Wavenet-B" },
  { code: "vi", name: "Vietnamese", voiceName: "vi-VN-Wavenet-B" },
  { code: "id", name: "Indonesian", voiceName: "id-ID-Wavenet-B" },
  { code: "th", name: "Thai", voiceName: "th-TH-Wavenet-B" },
  { code: "pl", name: "Polish", voiceName: "pl-PL-Wavenet-B" },
  { code: "uk", name: "Ukrainian", voiceName: "uk-UA-Wavenet-B" },
  { code: "ro", name: "Romanian", voiceName: "ro-RO-Wavenet-B" },
  { code: "nl", name: "Dutch", voiceName: "nl-NL-Wavenet-B" },
  { code: "sv", name: "Swedish", voiceName: "sv-SE-Wavenet-B" },
  { code: "fi", name: "Finnish", voiceName: "fi-FI-Wavenet-B" },
  { code: "no", name: "Norwegian", voiceName: "nb-NO-Wavenet-B" },
  { code: "da", name: "Danish", voiceName: "da-DK-Wavenet-B" },
  { code: "cs", name: "Czech", voiceName: "cs-CZ-Wavenet-B" },
  { code: "el", name: "Greek", voiceName: "el-GR-Wavenet-B" },
  { code: "he", name: "Hebrew", voiceName: "he-IL-Wavenet-B" },
  { code: "hu", name: "Hungarian", voiceName: "hu-HU-Wavenet-B" },
  { code: "uz", name: "Uzbek", voiceName: "uz-UZ-Standard-A" },
];
