export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag?: string;
}

export const languages: Language[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", flag: "🇸🇪" },
  { code: "da", name: "Danish", nativeName: "Dansk", flag: "🇩🇰" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", flag: "🇳🇴" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", flag: "🇫🇮" },
  { code: "cs", name: "Czech", nativeName: "Čeština", flag: "🇨🇿" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", flag: "🇭🇺" },
  { code: "ro", name: "Romanian", nativeName: "Română", flag: "🇷🇴" },
  { code: "bg", name: "Bulgarian", nativeName: "Български", flag: "🇧🇬" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", flag: "🇭🇷" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina", flag: "🇸🇰" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", flag: "🇸🇮" },
  { code: "et", name: "Estonian", nativeName: "Eesti", flag: "🇪🇪" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu", flag: "🇱🇻" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių", flag: "🇱🇹" },
  { code: "mt", name: "Maltese", nativeName: "Malti", flag: "🇲🇹" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", flag: "🇬🇷" },
  { code: "he", name: "Hebrew", nativeName: "עברית", flag: "🇮🇱" },
  { code: "th", name: "Thai", nativeName: "ไทย", flag: "🇹🇭" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  {
    code: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    flag: "🇮🇩",
  },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "tl", name: "Filipino", nativeName: "Filipino", flag: "🇵🇭" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "🇵🇰" },
  { code: "fa", name: "Persian", nativeName: "فارسی", flag: "🇮🇷" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская", flag: "🇧🇾" },
  { code: "ka", name: "Georgian", nativeName: "ქართული", flag: "🇬🇪" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն", flag: "🇦🇲" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan", flag: "🇦🇿" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақ", flag: "🇰🇿" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча", flag: "🇰🇬" },
  { code: "uz", name: "Uzbek", nativeName: "O'zbek", flag: "🇺🇿" },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ", flag: "🇹🇯" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол", flag: "🇲🇳" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली", flag: "🇳🇵" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල", flag: "🇱🇰" },
  { code: "my", name: "Burmese", nativeName: "မြန်မာ", flag: "🇲🇲" },
  { code: "km", name: "Khmer", nativeName: "ខ្មែរ", flag: "🇰🇭" },
  { code: "lo", name: "Lao", nativeName: "ລາວ", flag: "🇱🇦" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ", flag: "🇪🇹" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", flag: "🇹🇿" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá", flag: "🇳🇬" },
  { code: "ig", name: "Igbo", nativeName: "Igbo", flag: "🇳🇬" },
  { code: "ha", name: "Hausa", nativeName: "Hausa", flag: "🇳🇬" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu", flag: "🇿🇦" },
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans", flag: "🇿🇦" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa", flag: "🇿🇦" },
  { code: "st", name: "Southern Sotho", nativeName: "Sesotho", flag: "🇿🇦" },
  { code: "tn", name: "Tswana", nativeName: "Setswana", flag: "🇿🇦" },
  { code: "ss", name: "Swati", nativeName: "siSwati", flag: "🇸🇿" },
  { code: "ve", name: "Venda", nativeName: "Tshivenda", flag: "🇿🇦" },
  { code: "ts", name: "Tsonga", nativeName: "Xitsonga", flag: "🇿🇦" },
  {
    code: "nd",
    name: "Northern Ndebele",
    nativeName: "isiNdebele",
    flag: "🇿🇦",
  },
  {
    code: "nr",
    name: "Southern Ndebele",
    nativeName: "isiNdebele",
    flag: "🇿🇦",
  },
  { code: "sn", name: "Shona", nativeName: "chiShona", flag: "🇿🇼" },
  { code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda", flag: "🇷🇼" },
  { code: "lg", name: "Ganda", nativeName: "Luganda", flag: "🇺🇬" },
  { code: "ak", name: "Akan", nativeName: "Akan", flag: "🇬🇭" },
  { code: "tw", name: "Twi", nativeName: "Twi", flag: "🇬🇭" },
  { code: "ee", name: "Ewe", nativeName: "Eʋegbe", flag: "🇹🇬" },
  { code: "fon", name: "Fon", nativeName: "Fon", flag: "🇧🇯" },
  { code: "dyo", name: "Jola-Fonyi", nativeName: "Jola-Fonyi", flag: "🇸🇳" },
  { code: "wo", name: "Wolof", nativeName: "Wolof", flag: "🇸🇳" },
  { code: "ff", name: "Fulah", nativeName: "Fulfulde", flag: "🇨🇲" },
  { code: "bm", name: "Bambara", nativeName: "Bamanankan", flag: "🇲🇱" },
  { code: "dyu", name: "Dyula", nativeName: "Julakan", flag: "🇨🇮" },
  { code: "mos", name: "Mossi", nativeName: "Mòoré", flag: "🇧🇫" },
  { code: "dag", name: "Dagbani", nativeName: "Dagbanli", flag: "🇬🇭" },
  { code: "kpe", name: "Kpelle", nativeName: "Kpɛlɛwoo", flag: "🇱🇷" },
  { code: "vai", name: "Vai", nativeName: "Vai", flag: "🇱🇷" },
  { code: "men", name: "Mende", nativeName: "Mende", flag: "🇸🇱" },
  { code: "tem", name: "Timne", nativeName: "KʌThemnɛ", flag: "🇸🇱" },
  { code: "lun", name: "Lunda", nativeName: "Chilunda", flag: "🇿🇲" },
  { code: "bem", name: "Bemba", nativeName: "Ichibemba", flag: "🇿🇲" },
  { code: "ny", name: "Chichewa", nativeName: "Chichewa", flag: "🇲🇼" },
  { code: "tum", name: "Tumbuka", nativeName: "chiTumbuka", flag: "🇲🇼" },
  { code: "to", name: "Tongan", nativeName: "lea fakatonga", flag: "🇹🇴" },
  { code: "fj", name: "Fijian", nativeName: "vosa Vakaviti", flag: "🇫🇯" },
  { code: "sm", name: "Samoan", nativeName: "gagana fa'a Samoa", flag: "🇼🇸" },
  { code: "haw", name: "Hawaiian", nativeName: "ʻŌlelo Hawaiʻi", flag: "🇺🇸" },
  { code: "mi", name: "Maori", nativeName: "te reo Māori", flag: "🇳🇿" },
  { code: "ty", name: "Tahitian", nativeName: "Reo Tahiti", flag: "🇵🇫" },
  { code: "mg", name: "Malagasy", nativeName: "fiteny malagasy", flag: "🇲🇬" },
  { code: "so", name: "Somali", nativeName: "Soomaali", flag: "🇸🇴" },
  { code: "om", name: "Oromo", nativeName: "Afaan Oromoo", flag: "🇪🇹" },
  { code: "ti", name: "Tigrinya", nativeName: "ትግርኛ", flag: "🇪🇷" },
  { code: "aa", name: "Afar", nativeName: "Afaraf", flag: "🇩🇯" },
  { code: "dj", name: "Djibouti", nativeName: "Djibouti", flag: "🇩🇯" },
  { code: "co", name: "Corsican", nativeName: "corsu", flag: "🇫🇷" },
  { code: "br", name: "Breton", nativeName: "brezhoneg", flag: "🇫🇷" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg", flag: "🇬🇧" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge", flag: "🇮🇪" },
  { code: "gd", name: "Scottish Gaelic", nativeName: "Gàidhlig", flag: "🇬🇧" },
  { code: "kw", name: "Cornish", nativeName: "Kernewek", flag: "🇬🇧" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska", flag: "🇮🇸" },
  { code: "fo", name: "Faroese", nativeName: "føroyskt", flag: "🇫🇴" },
  { code: "gl", name: "Galician", nativeName: "galego", flag: "🇪🇸" },
  { code: "eu", name: "Basque", nativeName: "euskara", flag: "🇪🇸" },
  { code: "ca", name: "Catalan", nativeName: "català", flag: "🇪🇸" },
  { code: "oc", name: "Occitan", nativeName: "occitan", flag: "🇫🇷" },
  { code: "rm", name: "Romansh", nativeName: "rumantsch", flag: "🇨🇭" },
  { code: "fur", name: "Friulian", nativeName: "furlan", flag: "🇮🇹" },
  { code: "sc", name: "Sardinian", nativeName: "sardu", flag: "🇮🇹" },
  { code: "vec", name: "Venetian", nativeName: "vèneto", flag: "🇮🇹" },
  { code: "lmo", name: "Lombard", nativeName: "lombard", flag: "🇮🇹" },
  { code: "pms", name: "Piedmontese", nativeName: "piemontèis", flag: "🇮🇹" },
  { code: "lij", name: "Ligurian", nativeName: "lìgure", flag: "🇮🇹" },
  { code: "nap", name: "Neapolitan", nativeName: "napulitano", flag: "🇮🇹" },
  { code: "scn", name: "Sicilian", nativeName: "sicilianu", flag: "🇮🇹" },
  { code: "ast", name: "Asturian", nativeName: "asturianu", flag: "🇪🇸" },
  { code: "an", name: "Aragonese", nativeName: "aragonés", flag: "🇪🇸" },
  { code: "ext", name: "Extremaduran", nativeName: "estremeñu", flag: "🇪🇸" },
  { code: "lad", name: "Ladino", nativeName: "djudeo-espanyol", flag: "🇪🇸" },
  { code: "mir", name: "Mirandese", nativeName: "mirandés", flag: "🇵🇹" },
  { code: "mwl", name: "Mirandese", nativeName: "mirandés", flag: "🇵🇹" },
  {
    code: "frc",
    name: "Cajun French",
    nativeName: "français cadien",
    flag: "🇺🇸",
  },
  {
    code: "ht",
    name: "Haitian Creole",
    nativeName: "kreyòl ayisyen",
    flag: "🇭🇹",
  },
  { code: "jam", name: "Jamaican Patois", nativeName: "Patois", flag: "🇯🇲" },
  {
    code: "gsw",
    name: "Swiss German",
    nativeName: "Schwiizerdütsch",
    flag: "🇨🇭",
  },
  { code: "bar", name: "Bavarian", nativeName: "Boarisch", flag: "🇩🇪" },
  { code: "ksh", name: "Colognian", nativeName: "Kölsch", flag: "🇩🇪" },
  { code: "pfl", name: "Palatine German", nativeName: "Pälzisch", flag: "🇩🇪" },
  { code: "sli", name: "Lower Silesian", nativeName: "Schläsch", flag: "🇩🇪" },
  { code: "wae", name: "Walser", nativeName: "Walser", flag: "🇨🇭" },
  { code: "sxu", name: "Upper Saxon", nativeName: "Obersächsisch", flag: "🇩🇪" },
  {
    code: "vmf",
    name: "Main-Franconian",
    nativeName: "Mainfränkisch",
    flag: "🇩🇪",
  },
  { code: "sog", name: "Sogdian", nativeName: "سغدی", flag: "🇹🇯" },
  { code: "xcr", name: "Carian", nativeName: "Karian", flag: "🇹🇷" },
  { code: "xlc", name: "Lycian", nativeName: "Lycian", flag: "🇹🇷" },
  { code: "xld", name: "Lydian", nativeName: "Lydian", flag: "🇹🇷" },
  { code: "xlu", name: "Luwian", nativeName: "Luwian", flag: "🇹🇷" },
  { code: "xve", name: "Venetic", nativeName: "Venetic", flag: "🇮🇹" },
  { code: "xfa", name: "Faliscan", nativeName: "Faliscan", flag: "🇮🇹" },
  { code: "xum", name: "Umbrian", nativeName: "Umbrian", flag: "🇮🇹" },
  { code: "osc", name: "Oscan", nativeName: "Oscan", flag: "🇮🇹" },
  { code: "sga", name: "Old Irish", nativeName: "Goídelc", flag: "🇮🇪" },
  { code: "ang", name: "Old English", nativeName: "Englisc", flag: "🇬🇧" },
  {
    code: "fro",
    name: "Old French",
    nativeName: "ancien français",
    flag: "🇫🇷",
  },
  {
    code: "goh",
    name: "Old High German",
    nativeName: "Althochdeutsch",
    flag: "🇩🇪",
  },
  { code: "non", name: "Old Norse", nativeName: "Norrœnt mál", flag: "🇳🇴" },
  { code: "got", name: "Gothic", nativeName: "Gutiska razda", flag: "🇩🇪" },
  { code: "sla", name: "Slavic", nativeName: "Slavic", flag: "🇷🇺" },
  {
    code: "ine",
    name: "Indo-European",
    nativeName: "Indo-European",
    flag: "🌍",
  },
  { code: "gem", name: "Germanic", nativeName: "Germanic", flag: "🌍" },
  { code: "itc", name: "Italic", nativeName: "Italic", flag: "🌍" },
  { code: "cel", name: "Celtic", nativeName: "Celtic", flag: "🌍" },
  { code: "bal", name: "Baltic", nativeName: "Baltic", flag: "🌍" },
  { code: "sla", name: "Slavic", nativeName: "Slavic", flag: "🌍" },
  { code: "alb", name: "Albanian", nativeName: "Albanian", flag: "🌍" },
  { code: "arm", name: "Armenian", nativeName: "Armenian", flag: "🌍" },
  { code: "gre", name: "Greek", nativeName: "Greek", flag: "🌍" },
  { code: "ira", name: "Iranian", nativeName: "Iranian", flag: "🌍" },
  { code: "ind", name: "Indo-Aryan", nativeName: "Indo-Aryan", flag: "🌍" },
  { code: "dra", name: "Dravidian", nativeName: "Dravidian", flag: "🌍" },
  { code: "sem", name: "Semitic", nativeName: "Semitic", flag: "🌍" },
  { code: "ber", name: "Berber", nativeName: "Berber", flag: "🌍" },
  { code: "cus", name: "Cushitic", nativeName: "Cushitic", flag: "🌍" },
  { code: "omv", name: "Omotic", nativeName: "Omotic", flag: "🌍" },
  { code: "nub", name: "Nubian", nativeName: "Nubian", flag: "🌍" },
  { code: "nil", name: "Nilotic", nativeName: "Nilotic", flag: "🌍" },
  { code: "bnt", name: "Bantu", nativeName: "Bantu", flag: "🌍" },
  { code: "kho", name: "Khoisan", nativeName: "Khoisan", flag: "🌍" },
  { code: "afa", name: "Afro-Asiatic", nativeName: "Afro-Asiatic", flag: "🌍" },
  { code: "nub", name: "Nubian", nativeName: "Nubian", flag: "🌍" },
  { code: "fur", name: "Fur", nativeName: "Fur", flag: "🌍" },
  {
    code: "zgh",
    name: "Standard Moroccan Tamazight",
    nativeName: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
    flag: "🇲🇦",
  },
  { code: "shi", name: "Tachelhit", nativeName: "ⵜⴰⵛⵍⵃⵉⵜ", flag: "🇲🇦" },
  {
    code: "tzm",
    name: "Central Atlas Tamazight",
    nativeName: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
    flag: "🇲🇦",
  },
  { code: "rif", name: "Tarifit", nativeName: "ⵜⴰⵔⵉⴼⵉⵜ", flag: "🇲🇦" },
  { code: "kab", name: "Kabyle", nativeName: "Taqbaylit", flag: "🇩🇿" },
  { code: "cha", name: "Chamorro", nativeName: "Chamoru", flag: "🇬🇺" },
  { code: "mh", name: "Marshallese", nativeName: "Kajin M̧ajeļ", flag: "🇲🇭" },
  { code: "na", name: "Nauru", nativeName: "Dorerin Naoero", flag: "🇳🇷" },
  {
    code: "pau",
    name: "Palauan",
    nativeName: "a tekoi er a Belau",
    flag: "🇵🇼",
  },
  { code: "niu", name: "Niuean", nativeName: "ko e vagahau Niuē", flag: "🇳🇺" },
  {
    code: "rar",
    name: "Rarotongan",
    nativeName: "Māori Kūki 'Āirani",
    flag: "🇨🇰",
  },
  { code: "tkl", name: "Tokelauan", nativeName: "gagana Tokelau", flag: "🇹🇰" },
  { code: "tvl", name: "Tuvaluan", nativeName: "te 'gana Tūvalu", flag: "🇹🇻" },
  { code: "wls", name: "Wallisian", nativeName: "faka'uvea", flag: "🇼🇫" },
  { code: "fud", name: "Futunan", nativeName: "fakafutuna", flag: "🇼🇫" },
  { code: "nfr", name: "Norfuk", nativeName: "Norfuk", flag: "🇳🇫" },
  { code: "pis", name: "Pijin", nativeName: "Pijin", flag: "🇸🇧" },
  { code: "tpi", name: "Tok Pisin", nativeName: "Tok Pisin", flag: "🇵🇬" },
  { code: "hif", name: "Fiji Hindi", nativeName: "Fiji Hindi", flag: "🇫🇯" },
  { code: "bi", name: "Bislama", nativeName: "Bislama", flag: "🇻🇺" },
  { code: "cr", name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ", flag: "🇨🇦" },
  { code: "iu", name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ", flag: "🇨🇦" },
  { code: "oj", name: "Ojibwa", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ", flag: "🇨🇦" },
  { code: "nv", name: "Navajo", nativeName: "Diné bizaad", flag: "🇺🇸" },
  { code: "chr", name: "Cherokee", nativeName: "ᏣᎳᎩ", flag: "🇺🇸" },
  { code: "mus", name: "Creek", nativeName: "Mvskoke", flag: "🇺🇸" },
  { code: "cho", name: "Choctaw", nativeName: "Chahta Anumpa", flag: "🇺🇸" },
  { code: "dak", name: "Dakota", nativeName: "Dakhótiyapi", flag: "🇺🇸" },
  { code: "lkt", name: "Lakota", nativeName: "Lakȟótiyapi", flag: "🇺🇸" },
  { code: "apj", name: "Apache", nativeName: "Ndee biyáti'", flag: "🇺🇸" },
  {
    code: "apw",
    name: "Western Apache",
    nativeName: "Ndee biyáti'",
    flag: "🇺🇸",
  },
  {
    code: "apm",
    name: "Mescalero-Chiricahua Apache",
    nativeName: "Ndee biyáti'",
    flag: "🇺🇸",
  },
  { code: "apk", name: "Kiowa Apache", nativeName: "Ndee biyáti'", flag: "🇺🇸" },
  {
    code: "apc",
    name: "North Levantine Arabic",
    nativeName: "اللهجة الشامية الشمالية",
    flag: "🇸🇾",
  },
  {
    code: "apd",
    name: "Sudanese Arabic",
    nativeName: "اللهجة السودانية",
    flag: "🇸🇩",
  },
  {
    code: "arb",
    name: "Standard Arabic",
    nativeName: "العربية الفصحى",
    flag: "🇸🇦",
  },
  {
    code: "arq",
    name: "Algerian Arabic",
    nativeName: "اللهجة الجزائرية",
    flag: "🇩🇿",
  },
  {
    code: "ary",
    name: "Moroccan Arabic",
    nativeName: "اللهجة المغربية",
    flag: "🇲🇦",
  },
  {
    code: "arz",
    name: "Egyptian Arabic",
    nativeName: "اللهجة المصرية",
    flag: "🇪🇬",
  },
  {
    code: "afb",
    name: "Gulf Arabic",
    nativeName: "اللهجة الخليجية",
    flag: "🇶🇦",
  },
  {
    code: "ayh",
    name: "Hadrami Arabic",
    nativeName: "اللهجة الحضرمية",
    flag: "🇾🇪",
  },
  {
    code: "acw",
    name: "Hijazi Arabic",
    nativeName: "اللهجة الحجازية",
    flag: "🇸🇦",
  },
  {
    code: "ayl",
    name: "Libyan Arabic",
    nativeName: "اللهجة الليبية",
    flag: "🇱🇾",
  },
  {
    code: "acm",
    name: "Mesopotamian Arabic",
    nativeName: "اللهجة العراقية",
    flag: "🇮🇶",
  },
  {
    code: "ayp",
    name: "North Mesopotamian Arabic",
    nativeName: "اللهجة الموصلية",
    flag: "🇮🇶",
  },
  {
    code: "acx",
    name: "Omani Arabic",
    nativeName: "اللهجة العمانية",
    flag: "🇴🇲",
  },
  { code: "ayr", name: "Central Aymara", nativeName: "Aymar aru", flag: "🇧🇴" },
  { code: "ayc", name: "Southern Aymara", nativeName: "Aymar aru", flag: "🇵🇪" },
  {
    code: "quy",
    name: "Ayacucho Quechua",
    nativeName: "Chanka Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "quz",
    name: "Cusco Quechua",
    nativeName: "Qusqu Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qve",
    name: "Eastern Apurímac Quechua",
    nativeName: "Apurimaq Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qub",
    name: "Huallaga Huánuco Quechua",
    nativeName: "Wallaqa Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qup",
    name: "Southern Pastaza Quechua",
    nativeName: "Pastaza Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qul",
    name: "North Bolivian Quechua",
    nativeName: "Qhichwa",
    flag: "🇧🇴",
  },
  {
    code: "quh",
    name: "South Bolivian Quechua",
    nativeName: "Qhichwa",
    flag: "🇧🇴",
  },
  {
    code: "quf",
    name: "Lambayeque Quechua",
    nativeName: "Lambayeque Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qur",
    name: "Yanahuanca Pasco Quechua",
    nativeName: "Yanawanka Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qud",
    name: "Calderón Highland Quichua",
    nativeName: "Kichwa",
    flag: "🇪🇨",
  },
  {
    code: "qug",
    name: "Chimborazo Highland Quichua",
    nativeName: "Kichwa",
    flag: "🇪🇨",
  },
  {
    code: "quw",
    name: "Tena Lowland Quichua",
    nativeName: "Kichwa",
    flag: "🇪🇨",
  },
  {
    code: "qux",
    name: "Yauyos Quechua",
    nativeName: "Yawyu Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "quk",
    name: "Chachapoyas Quechua",
    nativeName: "Chachapuya Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qvc",
    name: "Cajamarca Quechua",
    nativeName: "Kashamarka Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qvm",
    name: "Margos-Yarowilca-Lauricocha Quechua",
    nativeName: "Margos Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qvn",
    name: "North Junín Quechua",
    nativeName: "Junin Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qvo",
    name: "Napo Lowland Quechua",
    nativeName: "Napu Kichwa",
    flag: "🇪🇨",
  },
  { code: "qxp", name: "Puno Quechua", nativeName: "Punu Qichwa", flag: "🇵🇪" },
  {
    code: "qxr",
    name: "Cañar Highland Quichua",
    nativeName: "Kichwa",
    flag: "🇪🇨",
  },
  {
    code: "qxt",
    name: "Santa Ana de Tusi Pasco Quechua",
    nativeName: "Tusi Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qxu",
    name: "Arequipa-La Unión Quechua",
    nativeName: "Ariqipa Qichwa",
    flag: "🇵🇪",
  },
  {
    code: "qxw",
    name: "Jauja Wanca Quechua",
    nativeName: "Wanka Qichwa",
    flag: "🇵🇪",
  },
  { code: "quj", name: "Joyabaj Quiché", nativeName: "K'iche'", flag: "🇬🇹" },
  {
    code: "qut",
    name: "West Central Quiché",
    nativeName: "K'iche'",
    flag: "🇬🇹",
  },
  { code: "qum", name: "Sipacapense", nativeName: "Sipakapense", flag: "🇬🇹" },
  { code: "qun", name: "Quenya", nativeName: "Quenya", flag: "🌍" },
  { code: "sjn", name: "Sindarin", nativeName: "Sindarin", flag: "🌍" },
  { code: "tlh", name: "Klingon", nativeName: "tlhIngan Hol", flag: "🌍" },
  { code: "doth", name: "Dothraki", nativeName: "Dothraki", flag: "🌍" },
  { code: "val", name: "Valyrian", nativeName: "Valyrian", flag: "🌍" },
  { code: "art", name: "Artificial", nativeName: "Artificial", flag: "🌍" },
  { code: "und", name: "Undefined", nativeName: "Undefined", flag: "🌍" },
  { code: "mul", name: "Multiple", nativeName: "Multiple", flag: "🌍" },
  {
    code: "zxx",
    name: "No linguistic content",
    nativeName: "No linguistic content",
    flag: "🌍",
  },
  {
    code: "mis",
    name: "Uncoded language",
    nativeName: "Uncoded language",
    flag: "🌍",
  },
  { code: "zbl", name: "Blissymbols", nativeName: "Blissymbols", flag: "🌍" },
  {
    code: "zsm",
    name: "Standard Malay",
    nativeName: "Bahasa Melayu Standard",
    flag: "🇲🇾",
  },
  {
    code: "zxx",
    name: "No linguistic content",
    nativeName: "No linguistic content",
    flag: "🌍",
  },
];

export const getLanguageByCode = (code: string): Language | undefined => {
  return languages.find((lang) => lang.code === code);
};

export const getLanguageName = (code: string): string => {
  const language = getLanguageByCode(code);
  return language ? language.name : code;
};

export const getLanguageNativeName = (code: string): string => {
  const language = getLanguageByCode(code);
  return language ? language.nativeName : code;
};

export const getLanguageFlag = (code: string): string => {
  const language = getLanguageByCode(code);
  return language ? language.flag || "🌍" : "🌍";
};

export const popularLanguages = languages.filter((lang) =>
  [
    "en",
    "es",
    "fr",
    "de",
    "it",
    "pt",
    "ru",
    "ja",
    "ko",
    "zh",
    "ar",
    "hi",
  ].includes(lang.code)
);

export const europeanLanguages = languages.filter((lang) =>
  [
    "en",
    "es",
    "fr",
    "de",
    "it",
    "pt",
    "ru",
    "nl",
    "pl",
    "sv",
    "da",
    "no",
    "fi",
    "cs",
    "hu",
    "ro",
    "bg",
    "hr",
    "sk",
    "sl",
    "et",
    "lv",
    "lt",
    "mt",
    "el",
  ].includes(lang.code)
);

export const asianLanguages = languages.filter((lang) =>
  [
    "ja",
    "ko",
    "zh",
    "hi",
    "th",
    "vi",
    "id",
    "ms",
    "tl",
    "bn",
    "ur",
    "fa",
    "he",
    "my",
    "km",
    "lo",
    "ne",
    "si",
  ].includes(lang.code)
);

export const africanLanguages = languages.filter((lang) =>
  [
    "ar",
    "sw",
    "yo",
    "ig",
    "ha",
    "zu",
    "af",
    "xh",
    "st",
    "tn",
    "ss",
    "ve",
    "ts",
    "nd",
    "nr",
    "sn",
    "rw",
    "lg",
    "ak",
    "tw",
    "ee",
    "fon",
    "dyo",
    "wo",
    "ff",
    "bm",
    "dyu",
    "mos",
    "dag",
    "kpe",
    "vai",
    "men",
    "tem",
    "lun",
    "bem",
    "ny",
    "tum",
  ].includes(lang.code)
);

export const americanLanguages = languages.filter((lang) =>
  [
    "en",
    "es",
    "pt",
    "fr",
    "ht",
    "jam",
    "frc",
    "cr",
    "iu",
    "oj",
    "nv",
    "chr",
    "mus",
    "cho",
    "dak",
    "lkt",
    "apj",
    "apw",
    "apm",
    "apk",
    "quy",
    "quz",
    "qve",
    "qub",
    "qup",
    "qul",
    "quh",
    "quf",
    "qur",
    "qud",
    "qug",
    "quw",
    "qux",
    "quk",
    "qvc",
    "qvm",
    "qvn",
    "qvo",
    "qxp",
    "qxr",
    "qxt",
    "qxu",
    "qxw",
    "quj",
    "qut",
    "qum",
  ].includes(lang.code)
);

export const oceanicLanguages = languages.filter((lang) =>
  [
    "to",
    "fj",
    "sm",
    "haw",
    "mi",
    "ty",
    "mg",
    "cha",
    "mh",
    "na",
    "pau",
    "niu",
    "rar",
    "tkl",
    "tvl",
    "wls",
    "fud",
    "nfr",
    "pis",
    "tpi",
    "hif",
    "bi",
  ].includes(lang.code)
);
